//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice_restful.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoaHoc
    {
        public string MaKhoaHoc { get; set; }
        public string TenKhoaHoc { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
        public Nullable<decimal> HocPhi { get; set; }
    }
}
